"""Sieve rule guidance for Mailroom setup.

Generates human-readable instructions for creating email routing rules.
No sieve introspection -- just prints what rules are needed for all
configured categories. A future milestone will add JMAP Contacts
migration and programmatic sieve rule creation.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from mailroom.setup.colors import BOLD, CYAN, DIM, GREEN, MAGENTA, color

if TYPE_CHECKING:
    from mailroom.core.config import MailroomSettings, ResolvedCategory


def generate_sieve_guidance(settings: MailroomSettings, *, ui_guide: bool = False) -> str:
    """Generate sieve rule guidance for all configured categories.

    Iterates over settings.resolved_categories, groups children under
    their parent for readability, and produces either copy-paste sieve-style
    snippets (default) or Fastmail Settings UI step-by-step instructions
    (when ui_guide=True).

    Args:
        settings: Mailroom config with resolved_categories and screener_mailbox.
        ui_guide: If True, show Fastmail UI instructions instead of sieve snippets.

    Returns:
        Full multiline guidance string.
    """
    all_cats = settings.resolved_categories
    roots = [c for c in all_cats if c.parent is None]
    children_of: dict[str, list[ResolvedCategory]] = {}
    for c in all_cats:
        if c.parent:
            children_of.setdefault(c.parent, []).append(c)

    if ui_guide:
        return _build_ui_guide(roots, children_of, settings.triage.screener_mailbox)
    return _build_sieve_snippets(roots, children_of, settings.triage.screener_mailbox)


def _format_category_rule(cat: ResolvedCategory, is_child: bool) -> list[str]:
    """Build sieve-snippet lines for a single category rule."""
    lines: list[str] = []
    name_display = color(cat.name, BOLD)

    if is_child:
        annotation = f"  (child of {cat.parent})"
    elif cat.add_to_inbox:
        annotation = f"  {color('(+Inbox)', GREEN)}"
    else:
        annotation = ""

    if cat.add_to_inbox and is_child:
        annotation += f"  {color('(+Inbox)', GREEN)}"

    lines.append(f"    {name_display}{annotation}")
    lines.append(f'      Condition: Sender is in contact group "{cat.contact_group}"')
    lines.append("      Actions:")

    mailbox_display = color(cat.destination_mailbox, CYAN)
    lines.append(f"        1. Add label: {mailbox_display}")

    if cat.add_to_inbox:
        lines.append(f"        2. {color('Continue to apply other rules', MAGENTA)}")
        lines.append(f"        {color('# No archive -- emails stay in Inbox via add_to_inbox', DIM)}")
    else:
        lines.append(f"        2. {color('Archive', MAGENTA)} (remove from Inbox)")
        lines.append(f"        3. {color('Continue to apply other rules', MAGENTA)}")

    return lines


def _build_sieve_snippets(
    roots: list[ResolvedCategory],
    children_of: dict[str, list[ResolvedCategory]],
    screener_mailbox: str,
) -> str:
    """Build default sieve-style snippet guidance."""
    lines: list[str] = []

    lines.append("Sieve Rules")
    lines.append("")
    lines.append("  Routing rules route incoming mail from categorized contacts to the")
    lines.append("  correct mailbox. Create these rules in Fastmail:")
    lines.append("    Settings > Filters & Rules > Add Rule")
    lines.append("")
    lines.append("  Note: Fastmail sieve cannot filter by contact group directly.")
    lines.append("  These rules must be created through the Fastmail UI, which uses")
    lines.append("  the jmapquery extension internally.")
    lines.append("")
    lines.append(
        f"  {color('IMPORTANT', BOLD)}: Every rule below MUST have "
        f'"{color("Continue to apply other rules", MAGENTA)}" enabled.'
    )
    lines.append("  Without this, additive labels from parent/child category rules will not fire.")
    lines.append('  In the Fastmail UI, this is the "then also apply other rules" checkbox.')
    lines.append("")
    lines.append("  Per-category rules:")

    for root in roots:
        lines.append("")
        lines.extend(_format_category_rule(root, is_child=False))

        # Emit sieve reference for root
        lines.append("")
        lines.append("      # Fastmail sieve equivalent (generated by the UI):")
        lines.append('      # require ["vnd.cyrus.jmapquery", "fileinto"];')
        lines.append("      # if jmapquery text:")
        lines.append(f'      # {{"fromContactGroupId":"<{root.contact_group}_GROUP_ID>"}}')
        lines.append("      # .")
        lines.append(f'      # {{ fileinto "INBOX.{root.destination_mailbox}"; }}')

        # Emit children under this root
        for child in children_of.get(root.name, []):
            lines.append("")
            lines.extend(_format_category_rule(child, is_child=True))

            lines.append("")
            lines.append("      # Fastmail sieve equivalent (generated by the UI):")
            lines.append('      # require ["vnd.cyrus.jmapquery", "fileinto"];')
            lines.append("      # if jmapquery text:")
            lines.append(f'      # {{"fromContactGroupId":"<{child.contact_group}_GROUP_ID>"}}')
            lines.append("      # .")
            lines.append(f'      # {{ fileinto "INBOX.{child.destination_mailbox}"; }}')

    lines.append("")
    lines.append("  Screener catch-all rule:")
    lines.append("")
    lines.append(f"    {screener_mailbox}")
    lines.append("      Condition: All other incoming mail (no specific sender match)")
    lines.append(f'      Action: Move to folder "{screener_mailbox}"')
    lines.append("")
    lines.append("      # This rule should be ordered LAST, after all category rules.")
    lines.append("      # It catches any mail not matched by the per-category rules above.")

    return "\n".join(lines)


def _build_ui_guide(
    roots: list[ResolvedCategory],
    children_of: dict[str, list[ResolvedCategory]],
    screener_mailbox: str,
) -> str:
    """Build Fastmail Settings UI step-by-step guidance."""
    lines: list[str] = []

    lines.append("Sieve Rules")
    lines.append("")
    lines.append("  Step-by-step instructions for creating routing rules in Fastmail.")
    lines.append("")
    lines.append("  For each rule below:")
    lines.append("    1. Go to Fastmail Settings > Filters & Rules")
    lines.append('    2. Click "Add Rule"')
    lines.append("    3. Set the condition and action as described")
    lines.append('    4. Check "Continue to apply other rules" (then also apply other rules)')
    lines.append('    5. Click "Save"')
    lines.append("    6. Ensure rules are ordered: category rules first, screener catch-all last")
    lines.append("")
    lines.append("  Per-category rules:")

    def _emit_ui_rule(cat: ResolvedCategory, is_child: bool) -> None:
        child_note = f"  (child of {cat.parent})" if is_child else ""
        lines.append("")
        lines.append(f"    {cat.name}{child_note}")
        lines.append(
            f'      Step 3a: Set condition to "Sender is in contact group" = "{cat.contact_group}"'
        )
        if cat.add_to_inbox:
            lines.append(
                f'      Step 3b: Set action to "Add label" = "{cat.destination_mailbox}"'
            )
            lines.append(
                '      Step 3c: Check "Continue to apply other rules"'
            )
            lines.append(
                "      Note: No archive step -- add_to_inbox keeps emails in Inbox"
            )
        else:
            lines.append(
                f'      Step 3b: Set action to "Add label" = "{cat.destination_mailbox}"'
            )
            lines.append(
                '      Step 3c: Set action to "Archive" (remove from Inbox)'
            )
            lines.append(
                '      Step 3d: Check "Continue to apply other rules"'
            )

    for root in roots:
        _emit_ui_rule(root, is_child=False)
        for child in children_of.get(root.name, []):
            _emit_ui_rule(child, is_child=True)

    lines.append("")
    lines.append("  Screener catch-all rule:")
    lines.append("")
    lines.append(f"    {screener_mailbox}")
    lines.append('      Step 3a: Set condition to "All messages" (or leave blank for catch-all)')
    lines.append(f'      Step 3b: Set action to "Move to folder" = "{screener_mailbox}"')
    lines.append("")
    lines.append("      Important: This rule must be LAST in the rule list.")

    return "\n".join(lines)
