"""Sieve rule guidance for Mailroom setup.

Generates human-readable instructions for creating email routing rules.
No sieve introspection -- just prints what rules are needed for all
configured categories. A future milestone will add JMAP Contacts
migration and programmatic sieve rule creation.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from mailroom.setup.colors import CYAN, color

if TYPE_CHECKING:
    from mailroom.core.config import MailroomSettings


def _highlight_folder(cat) -> str:
    """Return the folder name, colored cyan if it differs from the category name."""
    if cat.destination_mailbox != cat.name:
        return color(cat.destination_mailbox, CYAN)
    return cat.destination_mailbox


def generate_sieve_guidance(settings: MailroomSettings, *, ui_guide: bool = False) -> str:
    """Generate sieve rule guidance for all configured root categories.

    Iterates over settings._resolved_categories, skipping child categories
    (those with a non-None parent), and produces either copy-paste sieve-style
    snippets (default) or Fastmail Settings UI step-by-step instructions
    (when ui_guide=True).

    Args:
        settings: Mailroom config with _resolved_categories and screener_mailbox.
        ui_guide: If True, show Fastmail UI instructions instead of sieve snippets.

    Returns:
        Full multiline guidance string.
    """
    # Collect root categories (skip children -- they inherit routing from parent)
    root_categories = [
        cat for cat in settings._resolved_categories if cat.parent is None
    ]

    if ui_guide:
        return _build_ui_guide(root_categories, settings.screener_mailbox)
    return _build_sieve_snippets(root_categories, settings.screener_mailbox)


def _build_sieve_snippets(
    root_categories: list, screener_mailbox: str
) -> str:
    """Build default sieve-style snippet guidance."""
    lines: list[str] = []

    lines.append("Sieve Rules")
    lines.append("")
    lines.append("  Routing rules route incoming mail from categorized contacts to the")
    lines.append("  correct mailbox. Create these rules in Fastmail:")
    lines.append("    Settings > Filters & Rules > Add Rule")
    lines.append("")
    lines.append("  Note: Fastmail sieve cannot filter by contact group directly.")
    lines.append("  These rules must be created through the Fastmail UI, which uses")
    lines.append("  the jmapquery extension internally.")
    lines.append("")
    lines.append("  Per-category rules:")

    for cat in root_categories:
        folder_name = _highlight_folder(cat)
        lines.append("")
        lines.append(f"    {cat.name}")
        lines.append(f'      Condition: Sender is in contact group "{cat.contact_group}"')
        lines.append(f'      Action: Move to folder "{folder_name}"')
        lines.append("")
        lines.append("      # Fastmail sieve equivalent (generated by the UI):")
        lines.append('      # require ["vnd.cyrus.jmapquery", "fileinto"];')
        lines.append("      # if jmapquery text:")
        lines.append(f'      # {{"fromContactGroupId":"<{cat.contact_group}_GROUP_ID>"}}')
        lines.append("      # .")
        lines.append(f'      # {{ fileinto "INBOX.{folder_name}"; }}')

    lines.append("")
    lines.append("  Screener catch-all rule:")
    lines.append("")
    lines.append(f"    {screener_mailbox}")
    lines.append("      Condition: All other incoming mail (no specific sender match)")
    lines.append(f'      Action: Move to folder "{screener_mailbox}"')
    lines.append("")
    lines.append("      # This rule should be ordered LAST, after all category rules.")
    lines.append("      # It catches any mail not matched by the per-category rules above.")

    return "\n".join(lines)


def _build_ui_guide(root_categories: list, screener_mailbox: str) -> str:
    """Build Fastmail Settings UI step-by-step guidance."""
    lines: list[str] = []

    lines.append("Sieve Rules")
    lines.append("")
    lines.append("  Step-by-step instructions for creating routing rules in Fastmail.")
    lines.append("")
    lines.append("  For each rule below:")
    lines.append("    1. Go to Fastmail Settings > Filters & Rules")
    lines.append('    2. Click "Add Rule"')
    lines.append("    3. Set the condition and action as described")
    lines.append('    4. Click "Save"')
    lines.append("    5. Ensure rules are ordered: category rules first, screener catch-all last")
    lines.append("")
    lines.append("  Per-category rules:")

    for cat in root_categories:
        folder_name = _highlight_folder(cat)
        lines.append("")
        lines.append(f"    {cat.name}")
        lines.append(
            f'      Step 3a: Set condition to "Sender is in contact group" = "{cat.contact_group}"'
        )
        lines.append(
            f'      Step 3b: Set action to "Move to folder" = "{folder_name}"'
        )

    lines.append("")
    lines.append("  Screener catch-all rule:")
    lines.append("")
    lines.append(f"    {screener_mailbox}")
    lines.append('      Step 3a: Set condition to "All messages" (or leave blank for catch-all)')
    lines.append(f'      Step 3b: Set action to "Move to folder" = "{screener_mailbox}"')
    lines.append("")
    lines.append("      Important: This rule must be LAST in the rule list.")

    return "\n".join(lines)
